### ISSUE TITLE
vksdk #2

### ISSUE THREAD

**Issue by IvanMMM** [rayNymous/likeDrop#1]
Ещё одна проблема с вк модулем. Видимо отдаёт html.
    www-0 (err): SyntaxError: Unexpected token <
    www-0 (err):     at Object.parse (native)
    www-0 (err):     at IncomingMessage.<anonymous> (/root/bin/likeDrop/node_modules/vksdk/sdk.js:288:26)

**Comment by rayNymous** [comment]
да. похоже на хтмл.  позже добавлю обработку исключений для всех респонсов от  vksdk.

напиши кросспост в репозитарий https://github.com/57uff3r/nodejs-vksdk , ну или я напишу чуть позже.

**Comment by rayNymous** [comment]
добавил обработку исключений для респонсов. проверяй

**Comment by IvanMMM** [comment]
Пушни)

**Comment by rayNymous** [comment]
а это как оказалось проблема. новая винда и гит жалуется на пароль. пару минут

**Comment by rayNymous** [comment]
done

**Comment by rayNymous** [comment]
я её уже и закрывать боюсь. пусть открытой повисит
